### ISSUE TITLE
`tiny-benchy` module can be specified inside `devDependencies` instead of `dependencies`

### ISSUE THREAD

**Issue by semoal** [devongovett/tree-sitter-highlight#1]
Hi 👋 Devon!

Not sure about this, but just looking at the code I think it has to be specified inside `devDependencies`, I didn't find usage on the code itself.

Best regards

**Comment by devongovett** [comment]
Good catch! Fixed in bb608cfd14e325b9bcb4c2240eb400f5bf7cff5c
